function varargout=snpm(Action)
% SnPM: nonParametric statistical analysis toolbox for SPM
%_______________________________________________________________________
%  ___       ____  __  __   Statistical nonParametric Mapping toolbox
% / __) ___ (  _ \(  \/  )  Dpt of Statistics & Warwick Manufacturing Group
% \__ \( _ ) )___/ )    (   The University of Warwick
% (___/(_)_)(__)  (_/\/\_)  SnPM13 
%_______________________________________________________________________
%
% This is SnPM13, the SPM batch-compatible release of the nonParametric 
% toolbox for SPM
% SnPM13 is written for SPM8 and SPM12b -released Friday October 11th, 2013
%
% Please refer to this version as "SnPM13" in papers and
% communications.
%
%                           ----------------
%
% Please report bugs to spm-bugs@fil.ion.ucl.ac.uk. Peculiarities and
% general queries should be raised on the SPM discussion list. We will
% report patches to the list and make updates available if necessary.
%
%                           ----------------
%
% See the "About SnPM" topic (snpm.man) for information on using SnPM
%
% Additional information may be found at the SPMweb site:
%                  http://www.fil.ion.ucl.ac.uk/spm/snpm
% ...where details of the SPM email discussion list can be found:
%                  http://www.fil.ion.ucl.ac.uk/spm/help
%
%                           ----------------
%
%                SnPM, by Andrew Holmes and Thomas Nichols
%                   <snpm-authors@fil.ion.ucl.ac.uk>
%_______________________________________________________________________
% 
%	$Id$	

%-----------------------------functions-called------------------------
% spm
% spm_figure
% spm_help
% snpm_cp
% snpm_pp
% snpm_ui
%-----------------------------functions-called------------------------

%-Parameters
%-----------------------------------------------------------------------
SnPMver    = 'SnPM13';

%-Format arguments
%-----------------------------------------------------------------------
if nargin == 0, Action='Init'; end


if strcmp(lower(Action),lower('Init'))
%=======================================================================
global MODALITY
if isempty(spm_figure('FindWin','Menu'))
	spm('PET')
	clc
else
	clc
end
snpm_defaults;
[Finter,Fgraph,CmdLine] = spm('FnUIsetup','Statistical non-Parametric Mapping (SnPM)');
snpm_init; % Initialize Matlab Batch system
snpm('AsciiWelcome')
spm_help('!Disp','snpm.m','','Graphics',snpm('Ver'))
snpm('CreateMenuWin')

elseif strcmp(lower(Action),lower('CreateMenuWin'))
    fig = spm_figure('GetWin','Interactive');
    h0  = uimenu(fig,...
        'Label',	'SnPM13',...
        'Separator',	'on',...
        'Tag',		'SnPM13',...
        'HandleVisibility','on');
    h1  = uimenu(h0,...
        'Label',	'Specify',...
        'Separator',	'off',...
        'Tag',		'Specify',...
        'HandleVisibility','on');
    h1_1  = uimenu(h1,...
        'Label',	'SingleSub: Two Sample T test; 2 conditions, replications',...
        'Separator',	'off',...
        'Tag',		'TwoSampTss',...
        'CallBack','spm_jobman(''interactive'','''',''spm.tools.snpm.des.TwoSampTss'');',...
        'HandleVisibility','on');
    h1_2  = uimenu(h1,...
        'Label',	'SingleSub: Simple Regression (correlation); single covariate of interest',...
        'Separator',	'off',...
        'Tag',		'Corr1S',...
        'CallBack','spm_jobman(''interactive'','''',''spm.tools.snpm.des.Corr1S'');',...
        'HandleVisibility','on');
    h1_3  = uimenu(h1,...
        'Label',	'MultiSub: One Sample T test on diffs/contrasts',...
        'Separator',	'off',...
        'Tag',		'OneSampT',...
        'CallBack','spm_jobman(''interactive'','''',''spm.tools.snpm.des.OneSampT'');',...
        'HandleVisibility','on');
    h1_4  = uimenu(h1,...
        'Label',	'MultiSub: Simple Regression; 1 covariate of interest',...
        'Separator',	'off',...
        'Tag',		'Corr',...
        'CallBack','spm_jobman(''interactive'','''',''spm.tools.snpm.des.Corr'');',...
        'HandleVisibility','on');
    h1_5  = uimenu(h1,...
        'Label',	'MultiSub: Paired T test; 2 conditions, 1 scan per condition',...
        'Separator',	'off',...
        'Tag',		'PairT',...
        'CallBack','spm_jobman(''interactive'','''',''spm.tools.snpm.des.PairT'');',...
        'HandleVisibility','on');
    h1_6  = uimenu(h1,...
        'Label',	'Within Subject ANOVA, k diffs/contrasts per subject',...
        'Separator',	'off',...
        'Tag',		'ANOVAwithinS',...
        'CallBack','spm_jobman(''interactive'','''',''spm.tools.snpm.des.ANOVAwithinS'');',...
        'HandleVisibility','on');
    h1_7  = uimenu(h1,...
        'Label',	'2 Groups: Two Sample T test; 1 scan per subject',...
        'Separator',	'off',...
        'Tag',		'TwoSampT',...
        'CallBack','spm_jobman(''interactive'','''',''spm.tools.snpm.des.TwoSampT'');',...
        'HandleVisibility','on');
    h1_8  = uimenu(h1,...
        'Label',	'2 Groups: Test diff of response; 2 conditions, 1 scan per condition',...
        'Separator',	'off',...
        'Tag',		'TwoSampPairT',...
        'CallBack','spm_jobman(''interactive'','''',''spm.tools.snpm.des.TwoSampPairT'');',...
        'HandleVisibility','on');
    h1_9  = uimenu(h1,...
        'Label',	'Between group ANOVA; 1 scan per subject',...
        'Separator',	'off',...
        'Tag',		'ANOVAbtwnS',...
        'CallBack','spm_jobman(''interactive'','''',''spm.tools.snpm.des.ANOVAbtwnS'');',...
        'HandleVisibility','on');
    h2  = uimenu(h0,...
        'Label',	'Compute',...
        'Separator',	'off',...
        'Tag',		'Compute',...
        'CallBack','spm_jobman(''interactive'','''',''spm.tools.snpm.cp'');',...
        'HandleVisibility','on');
    h3  = uimenu(h0,...
        'Label',	'Inference',...
        'Separator',	'off',...
        'Tag',		'Inference',...
        'CallBack','spm_jobman(''interactive'','''',''spm.tools.snpm.inference'');',...
        'HandleVisibility','on');

elseif strcmp(lower(Action),lower('AsciiWelcome'))
%=======================================================================
disp( ' ___       ____  __  __                                                  ')
disp( '/ __) ___ (  _ \(  \/  )  Statistical nonParametric Mapping toolbox      ')
disp( '\__ \( _ ) )___/ )    (   University of Warwick')
disp(['(___/(_)_)(__)  (_/\/\_)  Version: ',snpm('Ver')])
fprintf('\n')


elseif strcmp(lower(Action),lower('Ver'))
%=======================================================================
% snpm('Ver')
varargout = {SnPMver};

elseif strcmp(lower(Action),lower('Colour'))
%=======================================================================
% snpm('Colour')
%-----------------------------------------------------------------------
% %-Developmental livery
% varargout = {[0.7,1.0,0.7], 'Lime Green'};
%-Distribution livery
varargout = {[0.8 0.8 1.0], 'Diluted Blackcurrent Purple'};

else
%=======================================================================
error('Unknown action string')

%=======================================================================
end
